import type { Profile, SocialLink, Skill, Statistic } from "@/types/content";
import type { Project, TimelineItem } from "@/types/content";

export const profile: Profile = {
  fullName: "Yordanos Bisrat",
  title: "Software Engineering Student | Aspiring Full-Stack Developer",
  bio: "Software Engineering student at Addis Ababa University, building full-stack products with Next.js and Supabase — and exploring everything from Flutter to OpenGL along the way.",
  location: "Addis Ababa, Ethiopia",
  email: "bisratyordanos777@gmail.com",
  resumeUrl: "#",
  yearsLearning: 3,
};

export const socialLinks: SocialLink[] = [
  { platform: "github", url: "https://github.com/YordanosBisrat", label: "GitHub" },
  { platform: "linkedin", url: "https://linkedin.com/in/yordanos-bisrat-911788334", label: "LinkedIn" },
  { platform: "leetcode", url: "https://leetcode.com/YordanosB/", label: "LeetCode" },
];

export const skills: Skill[] = [
  { id: "html", name: "HTML", category: "frontend", proficiency: 90 },
  { id: "css", name: "CSS", category: "frontend", proficiency: 85 },
  { id: "js", name: "JavaScript", category: "frontend", proficiency: 85 },
  { id: "ts", name: "TypeScript", category: "frontend", proficiency: 80 },
  { id: "react", name: "React", category: "frontend", proficiency: 82 },
  { id: "next", name: "Next.js", category: "frontend", proficiency: 78 },
  { id: "tailwind", name: "Tailwind CSS", category: "frontend", proficiency: 85 },
  { id: "node", name: "Node.js", category: "backend", proficiency: 70 },
  { id: "express", name: "Express", category: "backend", proficiency: 68 },
  { id: "rest", name: "REST APIs", category: "backend", proficiency: 75 },
  { id: "python", name: "Python", category: "languages", proficiency: 75 },
  { id: "java", name: "Java", category: "languages", proficiency: 65 },
  { id: "cpp", name: "C++", category: "languages", proficiency: 70 },
  { id: "dart", name: "Dart", category: "languages", proficiency: 70 },
  { id: "flutter", name: "Flutter", category: "mobile", proficiency: 72 },
  { id: "postgres", name: "PostgreSQL", category: "database", proficiency: 68 },
  { id: "mongo", name: "MongoDB", category: "database", proficiency: 60 },
  { id: "pandas", name: "Pandas", category: "ai", proficiency: 60 },
  { id: "numpy", name: "NumPy", category: "ai", proficiency: 60 },
  { id: "ml", name: "Machine Learning", category: "ai", proficiency: 55 },
  { id: "git", name: "Git", category: "tools", proficiency: 85 },
  { id: "figma", name: "Figma", category: "tools", proficiency: 65 },
  { id: "postman", name: "Postman", category: "tools", proficiency: 70 },
];

export const statistics: Statistic[] = [
  { label: "Projects", value: 8 },
  { label: "Technologies", value: 20, suffix: "+" },
  { label: "Languages", value: 5 },
  { label: "Repositories", value: 24, suffix: "+" },
  { label: "Years Learning", value: 3, suffix: "+" },
];


export const projects: Project[] = [
  {
    slug: "campus-collaboration-platform",
    title: "Campus Collaboration Platform",
    category: "mobile",
    summary: "A Flutter platform that helps university students exchange skills, discover study groups, and collaborate academically.",
    problem: "Students at AAU had no central place to find study groups or peers with complementary skills — coordination happened informally over scattered group chats.",
    solution: "Built a five-person team project with feature-based Flutter architecture, JWT auth, and role-based access, giving students a structured way to post, discover, and join study groups.",
    features: ["Skill exchange listings", "Study group discovery", "Role-based access", "Full CRUD on group content"],
    challenges: "Coordinating a five-person team around a shared Flutter codebase and agreeing on a feature-based folder structure that scaled as the app grew.",
    lessons: "Feature-based architecture pays off fast once more than one person is touching the codebase — file-type folders don't scale past a solo project.",
    techStack: ["Flutter", "Dart", "Node.js", "JWT"],
    githubUrl: "https://github.com/YordanosBisrat",
    isFeatured: true,
  },
  {
    slug: "addisreview-v2",
    title: "AddisReview V2",
    category: "web",
    summary: "A business discovery and review platform for Addis Ababa — search, rate, and review local businesses.",
    problem: "Finding reliable reviews of local businesses in Addis Ababa is hard — most review platforms are built around markets that don't reflect the local business landscape.",
    solution: "A full-stack React/Vite + Node/Express/SQLite app with JWT auth, letting users search, rate, and review businesses across the city.",
    features: ["Business search", "Star ratings + written reviews", "JWT-authenticated accounts", "Responsive UI"],
    challenges: "Designing a review moderation flow and a schema that could handle both business listings and nested review data cleanly in SQLite.",
    lessons: "Went through a senior-panel code review (6.5/10) that surfaced real gaps in error handling and query structure — invaluable for seeing how the code reads to someone else.",
    techStack: ["React", "Vite", "Node.js", "Express", "SQLite", "JWT"],
    githubUrl: "https://github.com/YordanosBisrat",
    isFeatured: true,
  },
  {
    slug: "minigit",
    title: "MiniGit",
    category: "systems",
    summary: "A custom version control system inspired by Git, built from scratch in C++.",
    problem: "Understanding how Git actually works under the hood — commits, trees, blobs — required building a simplified version rather than just reading about it.",
    solution: "Implemented core Git primitives (object storage, commit history, basic diffing) in C++ using object-oriented design and direct file handling.",
    features: ["Object storage model", "Commit history tracking", "File diffing", "Custom CLI"],
    challenges: "Designing the object storage layer to correctly track file states across commits without an existing library to lean on.",
    lessons: "Building a tool you use every day from scratch is the fastest way to actually understand it — abstractions stop being magic once you've implemented them.",
    techStack: ["C++", "Data Structures", "File I/O"],
    githubUrl: "https://github.com/YordanosBisrat",
    isFeatured: true,
  },
  {
    slug: "hierarchical-solar-system-simulator",
    title: "Hierarchical Solar System Simulator",
    category: "graphics",
    summary: "An OpenGL-based solar system simulator demonstrating hierarchical transformations and animation.",
    problem: "Computer graphics coursework required demonstrating a real understanding of hierarchical matrix transformations, not just using a library's built-in scene graph.",
    solution: "Built a solar system simulator in OpenGL/C++ with planets orbiting hierarchically around the sun, each with independent rotation and orbital speed.",
    features: ["Hierarchical transformation matrices", "Independent orbital + rotational animation", "Camera controls"],
    challenges: "A rendering bug in the transformation hierarchy caused child bodies to inherit incorrect parent rotations — traced and fixed before submission.",
    lessons: "Matrix transformation order matters enormously in hierarchical scenes — getting parent-child transform composition right took real debugging, not guesswork.",
    techStack: ["OpenGL", "C++", "Linear Algebra"],
    githubUrl: "https://github.com/YordanosBisrat",
    isFeatured: true,
  },
  {
    slug: "blame-the-director",
    title: "Blame the Director",
    category: "mobile",
    summary: "A movie review application built with Flutter using modern state management and API integration.",
    problem: "Wanted hands-on practice with BLoC state management and Dio for real API integration, beyond what Provider-based coursework covered.",
    solution: "A Flutter movie review app using BLoC for state management and Dio for networking against a movie API.",
    features: ["Movie search + details", "User reviews", "BLoC state management", "Dio-based API layer"],
    challenges: "Migrating mental models from Provider (used in an earlier assignment) to BLoC's stream-based architecture.",
    lessons: "BLoC's separation of events and state makes testing and reasoning about complex screens much easier once the initial learning curve is past.",
    techStack: ["Flutter", "BLoC", "Dio", "REST APIs"],
    githubUrl: "https://github.com/YordanosBisrat",
    isFeatured: true,
  },
];

export const timeline: TimelineItem[] = [
  { id: "start", label: "Started Software Engineering", date: "2023" },
  { id: "htmlcss", label: "HTML & CSS", date: "2023" },
  { id: "js", label: "JavaScript", date: "2023" },
  { id: "git", label: "Git & Version Control", date: "2024" },
  { id: "react", label: "React", date: "2024" },
  { id: "next", label: "Next.js", date: "2025" },
  { id: "flutter", label: "Flutter", date: "2025" },
  { id: "opengl", label: "OpenGL", date: "2025" },
  { id: "ai", label: "AI & Machine Learning", date: "2026" },
  { id: "fullstack", label: "Full-Stack Development", date: "2026" },
];